name: 自动部署 Workers
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # 允许手动/命令触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: 安装依赖
        run: pnpm install

      - name: 局部安装 wrangler
        run: pnpm install wrangler

      - name: 部署到 Cloudflare
        run: npx wrangler deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
